/*
 * tocio - GLSL/WebGL/Vulkan shader codegen. Emits a `vec4 OCIOMain(vec4)`
 * function plus a list of LUT texture descriptors the host uploads, following
 * OpenColorIO's GPU section model. 1D LUTs use an Nx1 sampler2D (portable
 * across ES3.0/330/450); 3D LUTs use sampler3D with hardware trilinear.
 *
 * Reimplemented from OpenColorIO's GPU path (BSD-3-Clause).
 *
 * Copyright (c) 2014-2026 Syoyo Fujita and TinyEXR authors
 * SPDX-License-Identifier: BSD-3-Clause
 */

#include "toc_internal.h"

static void emit_f(toc_sb *sb, float v) { toc_sb_decfloat(sb, v); }

static void emit_vec3(toc_sb *sb, float a, float b, float c) {
    toc_sb_puts(sb, "vec3(");
    emit_f(sb, a); toc_sb_putc(sb, ',');
    emit_f(sb, b); toc_sb_putc(sb, ',');
    emit_f(sb, c); toc_sb_putc(sb, ')');
}

static int sh_add_texture(toc_shader *sh, const toc_op *op, int idx) {
    toc_texture_desc *nt;
    toc_texture_desc *d;
    size_t cap = sh->num_textures + 1;
    nt = (toc_texture_desc *)toc_malloc(&sh->alloc, cap * sizeof(*nt));
    if (!nt) return 0;
    if (sh->textures) {
        memcpy(nt, sh->textures, sh->num_textures * sizeof(*nt));
        toc_free(&sh->alloc, sh->textures);
    }
    sh->textures = nt;
    d = &sh->textures[sh->num_textures++];
    memset(d, 0, sizeof(*d));
    /* sampler_name = ociolut<idx> */
    {
        char *p = d->sampler_name;
        const char *pre = "ociolut";
        int i = 0, v = idx;
        char tmp[12];
        int n = 0;
        while (pre[i]) p[i] = pre[i], ++i;
        if (v == 0) tmp[n++] = '0';
        while (v) { tmp[n++] = (char)('0' + v % 10); v /= 10; }
        while (n--) p[i++] = tmp[n];
        p[i] = 0;
    }
    if (op->kind == TOC_OP_LUT1D) {
        d->dim = TOC_TEX_2D;
        d->width = op->u.lut1d.length;
        d->height = 1;
        d->depth = 1;
        d->channels = op->u.lut1d.channels == 1 ? 1 : 3;
        d->data = op->u.lut1d.data;
        d->interp_linear = op->u.lut1d.interp != TOC_INTERP_NEAREST;
    } else {
        d->dim = TOC_TEX_3D;
        d->width = d->height = d->depth = op->u.lut3d.size;
        d->channels = 3;
        d->data = op->u.lut3d.data;
        d->interp_linear = 1;
    }
    return 1;
}

toc_result toc_emit_glsl(const toc_op_list *ops, toc_glsl_target target,
                         const toc_allocator *a, toc_shader *out) {
    toc_sb sb;
    size_t k;
    int tex_idx = 0;
    int vulkan = (target == TOC_GLSL_VULKAN450);
    if (!ops || !out) return TOC_ERROR_INVALID_ARGUMENT;
    if (!a) a = toc_default_allocator();
    memset(out, 0, sizeof(*out));
    out->alloc = *a;
    toc_sb_init(&sb, a);

    toc_sb_puts(&sb, "#version ");
    toc_sb_puts(&sb, target == TOC_GLSL_ES30 ? "300 es"
                     : target == TOC_GLSL_330 ? "330" : "450");
    toc_sb_putc(&sb, '\n');
    if (target == TOC_GLSL_ES30)
        toc_sb_puts(&sb, "precision highp float;\nprecision highp sampler3D;\n");
    toc_sb_puts(&sb,
                "// Generated by tocio. SPDX-License-Identifier: BSD-3-Clause\n"
                "// Color pipeline reimplemented from OpenColorIO "
                "(BSD-3-Clause).\n");

    /* sampler declarations (one per LUT op) */
    for (k = 0; k < ops->count; ++k) {
        const toc_op *op = &ops->ops[k];
        const char *styp;
        if (op->kind != TOC_OP_LUT1D && op->kind != TOC_OP_LUT3D) continue;
        styp = (op->kind == TOC_OP_LUT3D) ? "sampler3D" : "sampler2D";
        if (vulkan) {
            toc_sb_puts(&sb, "layout(binding=");
            toc_sb_int(&sb, tex_idx);
            toc_sb_puts(&sb, ") ");
        }
        toc_sb_puts(&sb, "uniform ");
        toc_sb_puts(&sb, styp);
        toc_sb_puts(&sb, " ociolut");
        toc_sb_int(&sb, tex_idx);
        toc_sb_puts(&sb, ";\n");
        if (!sh_add_texture(out, op, tex_idx)) { toc_sb_free(&sb); return TOC_ERROR_OUT_OF_MEMORY; }
        ++tex_idx;
    }

    toc_sb_puts(&sb, "vec4 OCIOMain(vec4 inPixel){\n  vec4 v = inPixel;\n");
    tex_idx = 0;
    for (k = 0; k < ops->count; ++k) {
        const toc_op *op = &ops->ops[k];
        switch (op->kind) {
            case TOC_OP_MATRIX: {
                const float *m = op->u.matrix.m, *o = op->u.matrix.off;
                int i;
                toc_sb_puts(&sb, "  v = mat4(");
                for (i = 0; i < 16; ++i) {
                    if (i) toc_sb_putc(&sb, ',');
                    emit_f(&sb, m[i]); /* GLSL mat4 is column-major == our m */
                }
                toc_sb_puts(&sb, ") * v + vec4(");
                emit_f(&sb, o[0]); toc_sb_putc(&sb, ',');
                emit_f(&sb, o[1]); toc_sb_putc(&sb, ',');
                emit_f(&sb, o[2]); toc_sb_putc(&sb, ',');
                emit_f(&sb, o[3]); toc_sb_puts(&sb, ");\n");
                break;
            }
            case TOC_OP_RANGE: {
                const float *s = op->u.range.scale, *o = op->u.range.offset;
                toc_sb_puts(&sb, "  v = v * vec4(");
                emit_f(&sb, s[0]); toc_sb_putc(&sb, ',');
                emit_f(&sb, s[1]); toc_sb_putc(&sb, ',');
                emit_f(&sb, s[2]); toc_sb_putc(&sb, ',');
                emit_f(&sb, s[3]); toc_sb_puts(&sb, ") + vec4(");
                emit_f(&sb, o[0]); toc_sb_putc(&sb, ',');
                emit_f(&sb, o[1]); toc_sb_putc(&sb, ',');
                emit_f(&sb, o[2]); toc_sb_putc(&sb, ',');
                emit_f(&sb, o[3]); toc_sb_puts(&sb, ");\n");
                if (op->u.range.clamp_lo || op->u.range.clamp_hi) {
                    toc_sb_puts(&sb, "  v = clamp(v, vec4(");
                    emit_f(&sb, op->u.range.clamp_lo ? op->u.range.min[0] : -1e30f);
                    toc_sb_puts(&sb, "), vec4(");
                    emit_f(&sb, op->u.range.clamp_hi ? op->u.range.max[0] : 1e30f);
                    toc_sb_puts(&sb, "));\n");
                }
                break;
            }
            case TOC_OP_EXPONENT:
                toc_sb_puts(&sb, "  v.rgb = pow(max(v.rgb, vec3(0.0)), ");
                emit_vec3(&sb, op->u.exponent.e[0], op->u.exponent.e[1],
                          op->u.exponent.e[2]);
                toc_sb_puts(&sb, ");\n");
                break;
            case TOC_OP_LOG:
                if (!op->u.log.inverse) {
                    toc_sb_puts(&sb, "  v.rgb = ");
                    emit_vec3(&sb, op->u.log.log_slope[0], op->u.log.log_slope[1],
                              op->u.log.log_slope[2]);
                    toc_sb_puts(&sb, " * log2(");
                    emit_vec3(&sb, op->u.log.lin_slope[0], op->u.log.lin_slope[1],
                              op->u.log.lin_slope[2]);
                    toc_sb_puts(&sb, " * v.rgb + ");
                    emit_vec3(&sb, op->u.log.lin_offset[0],
                              op->u.log.lin_offset[1], op->u.log.lin_offset[2]);
                    toc_sb_puts(&sb, ") / log2(");
                    emit_f(&sb, op->u.log.base);
                    toc_sb_puts(&sb, ") + ");
                    emit_vec3(&sb, op->u.log.log_offset[0],
                              op->u.log.log_offset[1], op->u.log.log_offset[2]);
                    toc_sb_puts(&sb, ";\n");
                } else {
                    toc_sb_puts(&sb, "  v.rgb = (pow(vec3(");
                    emit_f(&sb, op->u.log.base);
                    toc_sb_puts(&sb, "), (v.rgb - ");
                    emit_vec3(&sb, op->u.log.log_offset[0],
                              op->u.log.log_offset[1], op->u.log.log_offset[2]);
                    toc_sb_puts(&sb, ") / ");
                    emit_vec3(&sb, op->u.log.log_slope[0], op->u.log.log_slope[1],
                              op->u.log.log_slope[2]);
                    toc_sb_puts(&sb, ") - ");
                    emit_vec3(&sb, op->u.log.lin_offset[0],
                              op->u.log.lin_offset[1], op->u.log.lin_offset[2]);
                    toc_sb_puts(&sb, ") / ");
                    emit_vec3(&sb, op->u.log.lin_slope[0], op->u.log.lin_slope[1],
                              op->u.log.lin_slope[2]);
                    toc_sb_puts(&sb, ";\n");
                }
                break;
            case TOC_OP_CDL: {
                const float *L = op->u.cdl.luma;
                float lr = L[0], lg = L[1], lb = L[2];
                if (lr == 0 && lg == 0 && lb == 0) {
                    lr = 0.2126f; lg = 0.7152f; lb = 0.0722f;
                }
                toc_sb_puts(&sb, "  { vec3 c = v.rgb * ");
                emit_vec3(&sb, op->u.cdl.slope[0], op->u.cdl.slope[1],
                          op->u.cdl.slope[2]);
                toc_sb_puts(&sb, " + ");
                emit_vec3(&sb, op->u.cdl.offset[0], op->u.cdl.offset[1],
                          op->u.cdl.offset[2]);
                toc_sb_puts(&sb, ";\n");
                if (op->u.cdl.clamp)
                    toc_sb_puts(&sb, "  c = clamp(c, 0.0, 1.0);\n");
                toc_sb_puts(&sb, "  c = pow(c, ");
                emit_vec3(&sb, op->u.cdl.power[0], op->u.cdl.power[1],
                          op->u.cdl.power[2]);
                toc_sb_puts(&sb, ");\n  float L = dot(c, ");
                emit_vec3(&sb, lr, lg, lb);
                toc_sb_puts(&sb, ");\n  c = L + ");
                emit_f(&sb, op->u.cdl.saturation);
                toc_sb_puts(&sb, " * (c - L);\n");
                if (op->u.cdl.clamp)
                    toc_sb_puts(&sb, "  c = clamp(c, 0.0, 1.0);\n");
                toc_sb_puts(&sb, "  v.rgb = c; }\n");
                break;
            }
            case TOC_OP_LUT1D: {
                int N = op->u.lut1d.length, ch;
                static const char *comp[3] = {"r", "g", "b"};
                float dmin = op->u.lut1d.domain_min, dmax = op->u.lut1d.domain_max;
                for (ch = 0; ch < 3; ++ch) {
                    toc_sb_puts(&sb, "  v.");
                    toc_sb_puts(&sb, comp[ch]);
                    toc_sb_puts(&sb, " = texture(ociolut");
                    toc_sb_int(&sb, tex_idx);
                    toc_sb_puts(&sb, ", vec2((clamp((v.");
                    toc_sb_puts(&sb, comp[ch]);
                    toc_sb_puts(&sb, " - ");
                    emit_f(&sb, dmin);
                    toc_sb_puts(&sb, ") / ");
                    emit_f(&sb, dmax - dmin);
                    toc_sb_puts(&sb, ", 0.0, 1.0) * ");
                    emit_f(&sb, (float)(N - 1));
                    toc_sb_puts(&sb, " + 0.5) / ");
                    emit_f(&sb, (float)N);
                    toc_sb_puts(&sb, ", 0.5)).");
                    toc_sb_puts(&sb, op->u.lut1d.channels == 1 ? "r" : comp[ch]);
                    toc_sb_puts(&sb, ";\n");
                }
                ++tex_idx;
                break;
            }
            case TOC_OP_LUT3D: {
                int N = op->u.lut3d.size;
                const float *dn = op->u.lut3d.domain_min;
                const float *dx = op->u.lut3d.domain_max;
                toc_sb_puts(&sb, "  { vec3 u = clamp((v.rgb - ");
                emit_vec3(&sb, dn[0], dn[1], dn[2]);
                toc_sb_puts(&sb, ") / ");
                emit_vec3(&sb, dx[0] - dn[0], dx[1] - dn[1], dx[2] - dn[2]);
                toc_sb_puts(&sb, ", 0.0, 1.0);\n  v.rgb = texture(ociolut");
                toc_sb_int(&sb, tex_idx);
                toc_sb_puts(&sb, ", (u * ");
                emit_f(&sb, (float)(N - 1));
                toc_sb_puts(&sb, " + 0.5) / ");
                emit_f(&sb, (float)N);
                toc_sb_puts(&sb, ").rgb; }\n");
                ++tex_idx;
                break;
            }
            default: break;
        }
    }
    toc_sb_puts(&sb, "  return v;\n}\n");
    if (sb.oom) { toc_sb_free(&sb); toc_shader_free(out); return TOC_ERROR_OUT_OF_MEMORY; }
    out->source = toc_sb_take(&sb, NULL);
    return out->source ? TOC_SUCCESS : TOC_ERROR_OUT_OF_MEMORY;
}

void toc_shader_free(toc_shader *sh) {
    if (!sh) return;
    toc_free(&sh->alloc, sh->source);
    toc_free(&sh->alloc, sh->textures);
    sh->source = NULL;
    sh->textures = NULL;
    sh->num_textures = 0;
}
